### ISSUE TITLE
Server does not exist anymore: openwrt.draic.info

### ISSUE THREAD

**Issue by Byggvir** [Freifunk-Siegburg/ffsu-site#3]
The server openwrt.draic.info does not exist anymore.

`opkg_repo = 'http://openwrt.draic.info/barrier_breaker/14.07/%S/packages'`

**Comment by cmarxmeier** [comment]
and branch is ancient
changed in sereveral site.conf with pull requests to rsk branch:
openwrtmirror.example.com/chaos_calmer/15.05

Olli is on vacation so it will least a while until commit is accepted
